'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { addresses, publicClient } from '@/lib/genlayer/contracts';
import { formatGen } from '@/lib/validation/schemas';
import { withTimeout } from '@/lib/genlayer/read';
type Item={id:number;title:string;bounty:string;status:string;expiry:number;author:string;winner:string};
export default function Challenges(){
 const [items,setItems]=useState<Item[]>([]); const [state,setState]=useState<'loading'|'ready'|'error'>('loading');
 const load=()=>{setState('loading');void (async()=>{try{const count=Number(await withTimeout(publicClient.readContract({address:addresses.arena,functionName:'get_challenge_count'}) as Promise<bigint>));if(!Number.isFinite(count)||count<0)throw new Error('Malformed challenge count');const ids=Array.from({length:Math.min(count,200)},(_,i)=>BigInt(i+1));const rows=await withTimeout(Promise.all(ids.map(id=>publicClient.readContract({address:addresses.arena,functionName:'get_challenge',args:[id]}) as Promise<any>)));if(rows.some((x:any)=>!x||x.id===undefined||!x.title||!x.status))throw new Error('Malformed challenge response');setItems(rows.map((x:any)=>({id:Number(x.id),title:String(x.title),bounty:String(x.bounty),status:String(x.status),expiry:Number(x.expiry),author:String(x.author),winner:String(x.winner)})));setState('ready')}catch{setState('error')}})()}; useEffect(()=>{load()},[]);
 return <main className="page"><header><p className="eyebrow">CANONICAL ARENA / STUDIONET 61999</p><h1>Challenge wall</h1><p>Loaded from the deployed Arena contract. Public synthetic benchmark markers are never real secrets.</p></header>{state==='loading'&&<p>Loading canonical challenges…</p>}{state==='error'&&<><p className="error">Arena RPC unavailable, timed out, or returned malformed data.</p><button className="button" onClick={load}>retry read</button></>}{state==='ready'&&items.length===0&&<p>No challenges have been created yet.</p>}<div className="challenge-wall">{items.map(x=><Link href={`/x/${x.id}`} className="challenge-card" key={x.id}><div><span className="seal">{x.status}</span><span>#{String(x.id).padStart(3,'0')}</span></div><h2>{x.title}</h2><p>{x.author}</p><footer><b>{formatGen(BigInt(x.bounty))}</b><span>{x.winner!=='0x0000000000000000000000000000000000000000'?'winner '+x.winner:'expiry '+(x.expiry?new Date(x.expiry*1000).toLocaleString():'not active')}</span></footer></Link>)}</div></main>
}
