'use client';
import { useState } from 'react'; import { attackSchema } from '@/lib/validation/schemas'; import { TxStatus } from './tx-status'; import { useWallet } from '@/lib/wallet/provider'; import { submitAndConfirm, TxState } from '@/lib/genlayer/transaction'; import { addresses, publicClient } from '@/lib/genlayer/contracts';
const hash=(text:string)=>crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)).then(b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join(''));
export function AttackLab({id}:{id:string}){const [payload,setPayload]=useState('');const [salt,setSalt]=useState('');const [commit,setCommit]=useState('');const [attackId,setAttackId]=useState('1');const [warning,setWarning]=useState(false);const [error,setError]=useState('');const [tx,setTx]=useState<TxState>({phase:'IDLE'});const w=useWallet();
 const prepare=async()=>{const fresh=crypto.getRandomValues(new Uint8Array(24));const s=btoa(String.fromCharCode(...fresh));try{attackSchema.parse({payload,salt:s});setSalt(s);setCommit(await hash(`${id}:${w.account}:${payload}:${s}`));setWarning(true);setError('')}catch{setError('Payload must be 1–1600 characters.')}};
 const download=()=>{const blob=new Blob([JSON.stringify({challengeId:id,attacker:w.account,payload,salt,commitment:commit},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cantrap-attack-${id}.json`;a.click();URL.revokeObjectURL(a.href)};
 const commitTx=()=>{if(!w.client||!w.onStudionet||!w.account){setTx({phase:'WRONG_NETWORK',error:'Connect a wallet on Studionet first.'});return}void submitAndConfirm(w.client,{address:addresses.arena,functionName:'commit_attack',args:[BigInt(id),commit]},async()=>{const value=await publicClient.readContract({address:addresses.arena,functionName:'get_active_attack_id',args:[BigInt(id),w.account!]});setAttackId(String(value));return value},setTx)};
 const revealTx=()=>{if(!w.client||!w.onStudionet){setTx({phase:'WRONG_NETWORK',error:'Connect a wallet on Studionet first.'});return}void submitAndConfirm(w.client,{address:addresses.arena,functionName:'reveal_attack',args:[BigInt(attackId),payload,salt]},async()=>undefined,setTx)};
 const testTx=()=>{if(!w.client||!w.onStudionet){setTx({phase:'WRONG_NETWORK',error:'Connect a wallet on Studionet first.'});return}void submitAndConfirm(w.client,{address:addresses.arena,functionName:'test_attack',args:[BigInt(attackId)]},async()=>undefined,setTx)};
 return <div className="lab"><p className="eyebrow">ATTACK LAB / LOCAL MATERIAL UNTIL REVEAL</p><textarea value={payload} onChange={e=>setPayload(e.target.value)} placeholder="Write a sandbox attack payload. This is never sent before the commit transaction." maxLength={1600}/><div className="lab-meta"><span>{payload.length}/1600</span><button onClick={prepare} className="button">generate commitment</button></div>{error&&<p className="error">{error}</p>}{commit&&<section className="hash-tape"><label>COMMITMENT HASH</label><code>{commit}</code><button onClick={download}>download local receipt ↓</button></section>}{warning&&<section className="warning"><b>Store your salt locally only if you understand the risk.</b> Losing it means this commitment cannot be revealed. <button onClick={()=>{localStorage.setItem(`cantrap:${id}:${commit}`,salt);setWarning(false)}}>I understand — save locally</button></section>}<button className="button danger" disabled={!commit} onClick={commitTx}>commit attack →</button><div className="lab-meta"><label>CANONICAL ATTACK ID <input value={attackId} readOnly /></label><button className="button" disabled={attackId==='0'} onClick={revealTx}>reveal after delay →</button><button className="button" disabled={attackId==='0'} onClick={testTx}>run consensus test →</button></div><TxStatus tx={tx}/></div>}
