'use client';
import { useEffect, useState } from 'react';
import { addresses, publicClient } from '@/lib/genlayer/contracts';
import { formatGen } from '@/lib/validation/schemas';
import { submitAndConfirm, TxState } from '@/lib/genlayer/transaction';
import { useWallet } from '@/lib/wallet/provider';
import { TxStatus } from './tx-status';
type Vault = { amount: string; funded_at: number; state: string; recipient?: string; transfer_kind?: string; dispatched_at?: number };
export function VaultState({ challenge }: { challenge: any }) {
  const w = useWallet(); const [vault, setVault] = useState<Vault | null>(null); const [status, setStatus] = useState<'loading'|'ready'|'error'>('loading'); const [now, setNow] = useState(() => Math.floor(Date.now()/1000)); const [tx, setTx] = useState<TxState>({phase:'IDLE'});
  const refresh = async () => { try { setVault(await publicClient.readContract({address: addresses.vault, functionName: 'get_vault', args: [BigInt(challenge.id)]}) as Vault); setStatus('ready'); } catch { setStatus('error'); } };
  useEffect(() => { void refresh(); const timer=window.setInterval(()=>setNow(Math.floor(Date.now()/1000)),1000); return () => window.clearInterval(timer); }, [challenge.id]);
  const isAuthor = !!w.account && String(w.account).toLowerCase()===String(challenge.author).toLowerCase(); const isWinner = !!w.account && String(w.account).toLowerCase()===String(challenge.winner).toLowerCase(); const funded = vault?.state === 'FUNDED'; const unactivatedAt = vault ? Number(vault.funded_at)+Number(challenge.activation_timeout||86400) : 0; const unactivatedEligible = challenge.status==='FUNDED' && isAuthor && funded && now>=unactivatedAt; const claimEligible = challenge.status==='BROKEN' && isWinner && funded; const expiredEligible = challenge.status==='EXPIRED' && isAuthor && funded; const dispatch = (functionName:string) => { if (!w.client || !w.onStudionet) { setTx({phase:'WRONG_NETWORK',error:'Connect a wallet on Studionet first.'}); return; } void submitAndConfirm(w.client,{address:addresses.vault,functionName,args:[BigInt(challenge.id)]},async()=>{await refresh();const current=await publicClient.readContract({address:addresses.vault,functionName:'get_vault',args:[BigInt(challenge.id)]}) as any;return current.state==='TRANSFER_DISPATCHED'?true:{ok:false,error:`Vault state is ${current.state}; expected TRANSFER_DISPATCHED.`};},setTx); };
  const countdown = Math.max(0, unactivatedAt-now); const countdownText = `${Math.floor(countdown/3600)}h ${Math.floor((countdown%3600)/60)}m ${countdown%60}s`;
  return <section className="notice"><b>Canonical Vault state</b>{status==='loading'&&<p>Loading escrow state…</p>}{status==='error'&&<p className="error">Vault entry unavailable or RPC failed.</p>}{status==='ready'&&vault&&<><p>{formatGen(BigInt(vault.amount))} · {vault.state}</p><p>Funded: {new Date(Number(vault.funded_at)*1000).toLocaleString()}</p>{vault.state==='TRANSFER_DISPATCHED'&&<p>Transfer dispatched to {vault.recipient} · {vault.transfer_kind} · {vault.dispatched_at ? new Date(Number(vault.dispatched_at)*1000).toLocaleString() : 'time unavailable'}</p>}{vault.state==='FUNDED'&&challenge.status==='FUNDED'&&isAuthor&&!unactivatedEligible&&<p>Unactivated refund available in {countdownText}.</p>}{claimEligible&&<button className="button danger" onClick={()=>dispatch('claim_bounty')}>dispatch bounty</button>}{unactivatedEligible&&<button className="button danger" onClick={()=>dispatch('refund_unactivated')}>dispatch unactivated refund</button>}{expiredEligible&&<button className="button danger" onClick={()=>dispatch('refund_expired')}>dispatch expired refund</button>}{(claimEligible||unactivatedEligible||expiredEligible)&&<p>Only transfer dispatch is confirmed; recipient settlement is external.</p>}</>}{status==='ready'&&vault?.state==='TRANSFER_DISPATCHED'&&<p>No further dispatch is available for this escrow.</p>}<TxStatus tx={tx}/></section>;
}
